tls:
  certificates:
    - certFile: /certs/cert.pem
      keyFile: /certs/key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/cert.pem
        keyFile: /certs/key.pem

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    http-catchall:
      rule: "hostregexp(`{host:.+}`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop@internal

    websecure-catchall:
      rule: "hostregexp(`{host:.+}`)"
      entryPoints:
        - websecure
      service: noop@internal
      tls: {}

{{ if ne .Env.CERT_RESOLVER "" }}
certificatesResolvers:
  {{ .Env.CERT_RESOLVER }}:
    acme:
      email: {{ .Env.LETSENCRYPT_EMAIL }}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
{{ end }}